### ISSUE TITLE
源代码查看使用 100vw - 10px 问题

### ISSUE THREAD

**Issue by nenge123** [aieditor-team/AiEditor#112]
使用vw会导致溢出文件,建议改成100%
```css
.aie-container [data-tippy-root] {
    max-width: calc(100vw - 10px); 
}
```

![捕获](https://github.com/user-attachments/assets/63b88bc7-1d7b-4cf8-8db3-50e734ecdbed)

建议使用gird去定义这种框,这样他总会按照当前主容器大小占满,
从而减少``` max-width: calc(100vw - 10px); ```等计算,因为flex会不占满容器!

清除```.aie-popover-content``` =>``` /* width: 850px; *//* max-width: calc(100% - 10px); */ ```

```css
.aie-container [data-tippy-root] {
    width: calc(100% - 10px);
    max-width: 1000px !important;

}
aie-container .tippy-box {
/** max-width: 1000px !important; **/
}
.aie-popover{
    display: grid;
    align-items: stretch;
    justify-items: stretch;
    grid-template-columns: auto;
    grid-template-areas:
        "header"
        "content"
        "footer";
    grid-template-rows: max-content auto max-content;
}
.aie-popover-header{
    grid-area: header;
}
.aie-popover-content{
    grid-area: content;
}
.aie-popover-footer{
    grid-area: footer;
}
```
